### ISSUE TITLE
error in GBA method (classify_acr_aca): ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by emmaver** [HaidYi/acrfinder#3]
Hello,

I have a collection of around 5000 bacterial genomes, and for all except 6 I managed to run the AcrFinder. In the 6 specific cases, I encountered this error:

```
Traceback (most recent call last):
  File "acr_aca_cri_runner.py", line 335, in <module>
    classify_acr_aca(BLAST_FILE, CRISPR_NAME_maps_SEQ_NAME, ACR_ACA_FILE, OUTPUT_DIR, INTERMEDIATES, BLAST_SLACK, ESCAPE_DBFILE, CDD_DBFILE, GENOME_TYPE)	# classifies Acr/Aca proteins
  File "acr_aca_cri_runner.py", line 210, in classify_acr_aca
    blastHitStart, blastHitEnd, target_accession = startEnd.split('-')
ValueError: too many values to unpack (expected 3)
```
The result file is generated but doesn't contain the self-targeting spacer columns, nor the confidence level.
I understand something is wrong with the blastn result file from blasting the spacers against the masked genome, so I added an example here: [blast_out.txt](https://github.com/HaidYi/acrfinder/files/4332464/blast_out.txt)

Thanks in advance for your help,
Emma

**Comment by linnabrown** [comment]
Hi Emma,
Thank you very much for using our tool. Haidong is getting a disease and needs some rest today. So we could not respond to you very early.  We will check the problem as soon as possible. Thank you for your attention.
Le

**Comment by linnabrown** [comment]
This problem may incurred by the ID of your input sequence with hypen("-")and underscore("_"). We will consider this case into our code and fix this as soon as possible.

**Comment by emmaver** [comment]
Hello Le,
These samples indeed (exceptionally) have a hyphen in the contig headers. Thanks a lot.
Emma

**Comment by linnabrown** [comment]
> Hello Le,
> These samples indeed (exceptionally) have a hyphen in the contig headers. Thanks a lot.
> Emma

Thanks a lot. The reason to cause this problem is line 167.

https://github.com/HaidYi/acrfinder/blob/f135e14f8aae172c51495f99d87839291e228f5a/acr_aca_cri_runner.py#L167

Haidong will use a tuple instead to represent the key of `START_END_maps_BLAST_HIT `.

**Comment by linnabrown** [comment]
I updated in dev branch. @HaidYi  Please check it out, thanks a lot.

**Comment by linnabrown** [comment]
@emmaver  Sorry for waiting long time because of this severe time you know. Hope you are in good health, too. Haidong tonight will merge the code if it works well, and then update the docker in our image and on the dockerhub. Thank you for your attention and patient!

**Comment by HaidYi** [comment]
@emmaver  The code has been updated on dev branch and you can checkout to dev branch to run your code. We will merge it after several stable commits. If you have any questions, feel free to contact me. Hope you stay healthy at this particular time.

HD

**Comment by emmaver** [comment]
Thank you very much. I didn't manage to test it yet but if there is a problem I will come back to you.
I hope you stay healthy as well. Fortunately as bioinformaticians we can continue working in these crisis times :)
