### ISSUE TITLE
AcrIIA16 missing in known-acr.faa

### ISSUE THREAD

**Issue by emmaver** [HaidYi/acrfinder#4]
Hello,

Could it be that AcrIIA16 sequence is missing from the known-acr.faa file?
It is recorded as a known Acr gene [here](https://docs.google.com/spreadsheets/d/17BR_Cy2jmokSKVZQwq7U6QgMUCUM5OBjnVnWbmsc6Eg/edit#gid=1244120310).

Best,
Emma

**Comment by linnabrown** [comment]
Thank you very much Emma, we will give you the feedback ASAP.

**Comment by linnabrown** [comment]
Hello Emma. We know that AcrIIA16 sequence is really missing. Bowen will update the known-acr.faa file as soon as possible. It also will be updated in our docker tonight, too. Thanks a lot.

Best,
Le

**Comment by HaidYi** [comment]
@emmaver AcrIIA16 has been added to known acr.
