### ISSUE TITLE
python version conflict

### ISSUE THREAD

**Issue by Stephen8554** [HaidYi/acrfinder#5]
Hi! Following your guidance, I installed CRISPRCasFinder firstly. However, the process runs into some errors during cas genes detection after finishing CRISPR genes detection. 

> Request:  Single Genome, Phase:  Gene Finding
Finding genes in sequence #1 (526169 bp)...done!
Traceback (most recent call last):
  File "/opt/AcrFinder/acrfinder-master/dependencies/CRISPRCasFinder/bin/macsyfinder", line 37, in <module>
    from macsypy.search_systems import search_systems
  File "/opt/AcrFinder/acrfinder-master/dependencies/CRISPRCasFinder/macsyfinder-1.0.5/macsypy/search_systems.py", line 1027
            """
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 685-686: truncated \uXXXX escape
No Cas results
Nb of Cas in this sequence = 0
Secondary folders/files (Prodigal, CasFinder, rawFASTA, CRISPRFinderProperties) have been created

All CRISPRs = 9
All Cas = 0

CRISPRCasFinder will call the macsyFinder to detect cas genes. **MacsyFinder requires [Python2.7 ](https://macsyfinder.readthedocs.io/en/latest/installation.html)while your  README.md says that Python3.4 or new version is required to run AcrFinder.**

**Comment by linnabrown** [comment]
Thank you for using our tool. In your sever you need both install python 2.7 and python 3.* But python3.* should be your main python interpreter. We will clarify this point about this.

Also, we recommend you to use docker to install our tool. Just one step to build all requirements
```
docker pull [OPTIONS] haidyi/acrfinder:latest
```

or you can install it by github

```
git clone https://github.com/haidyi/acrfinder.git
cd acrfinder
docker build -t [tag name] .
```

**Comment by Stephen8554** [comment]
Thanks! I am installing AcrFinder with docker. There are some problems occurred.

> [root@wanglab4 test]# docker pull haidyi/acrfinder:latest
latest: Pulling from haidyi/acrfinder
df7e5105b466: Extracting [===========>                                       ] 833.9 MB/3.752 GB
f068f206b7d8: Download complete 
64322be39581: Download complete 
e8610d37ffa9: Download complete 
d20f93c749c5: Download complete 
d14e585437d2: Download complete 
7454ee621e34: Download complete 
341582a6ed28: Download complete 
cf16b54d0273: Download complete 
aa0c732f38e9: Download complete 
949ea3fc7e52: Download complete 
cb58b97a95fd: Download complete 
b6c9d3505751: Download complete 
52e45d550808: Already exists 
3d1c7fcbd1dc: Already exists 
4e1bf54cd3be: Already exists 
a818d3439bf9: Already exists 
aec622c79675: Already exists 
d31d50821393: Already exists 
1e5f2a0719e4: Already exists 
0355e5d64e93: Already exists 
c46965895385: Already exists 
993e7910424c: Already exists 
0c2ac6811355: Already exists 
2d148493030a: Already exists 
2ff496487397: Already exists 
08bea033bc82: Already exists 
66f69e14fa74: Already exists 
4e8628b6d9ef: Already exists 
f3691f9df8a0: Already exists 
836315858273: Already exists 
b3fac6e69f95: Already exists 
e360b68cdc9a: Already exists 
85c2b42f5508: Already exists 
5d71ec22151b: Already exists 
8e0e33ba157d: Already exists 
Pulling repository haidyi/acrfinder
Could not reach any registry endpoint

**Comment by linnabrown** [comment]
we will give you the feedback asap.

**Comment by linnabrown** [comment]
Hi Stephen8554 . We just docker pull the pkg in a new server, but there is no this kind of error like yours. Did you try this command twice? If so, you need you remove these existing images. 
For example.
```
docker rmi 52e45d550808 
docker rmi 836315858273
...
```

**Comment by Stephen8554** [comment]
Hi linnabrown! I have updated my server from CentOS 6 to CentOS 7. And I have pulled the package from Doker Hub successfully. However, another problem occurred. I could not enter the interactive mode when I start the acrfinder.
`[chengzhi@localhost ~]$ docker run haidyi/acrfinder /bin/bash
[chengzhi@localhost ~]$ docker container ls -a               
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
b8532ad291f9        haidyi/acrfinder    "/bin/bash"         6 minutes ago       Exited (0) 6 minutes ago                       pensive_franklin
[chengzhi@localhost ~]$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.13.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.44GiB
 Name: localhost.localdomain
 ID: QOFX:YU4S:2AWA:YQQQ:R6GE:NRH2:GQI7:7V3V:WR4W:5SZ7:RTZZ:5IZT
 Docker Root Dir: /home/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**Comment by Stephen8554** [comment]
Hi linnabrown! I have installed acrfinder successfully. I install Ubuntu 20.04.1 and pull the image from Docker Hub. Then copy the GCF_000210795.2 from the sample_organisms folder to my home folder. Finally, I run the following command and get the results successfully!
`docker run --rm -it -v ~/GCF_000210795.2:/app/acrfinder/GCF_000210795.2 haidyi/acrfinder:latest python3 acr_aca_cri_runner.py -n GCF_000210795.2/GCF_000210795.2_genomic.fna -f GCF_000210795.2/GCF_000210795.2_genomic.gff -a GCF_000210795.2/GCF_000210795.2_protein.faa -o GCF_000210795.2/output_dir -z B -c 2 -p true -g true`

Thanks for your help and I will close this issue.

**Comment by linnabrown** [comment]
Perfect
